Django_instaclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),  # accounts app url 연결
    path('accounts/', include('allauth.urls')),

    path('post/', include('post.urls', namespace='post')),  # post app url 연결
    # 루트 URL로 접근할 때 post로 연결
    path('', lambda r: redirect('post:post_list'), name='root'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login_check, name='login'),
    path('logout/', logout, name='logout'),
    path('follow/', follow, name="follow"),
]

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('new/', post_new, name='post_new'),  # 새 포스트 작성 url
    path('edit/<int:pk>/', post_edit, name='post'
                                           '_edit'),  # <int:pk> 키값.
    path('delete/<int:pk>/', post_delete, name='post_delete'),
    path('like/', post_like, name="post_like"),
    path('bookmark/', post_bookmark, name="post_bookmark"),
    path('comment/new/', comment_new, name="comment_new"),
    path('comment/delete/', comment_delete, name='comment_delete'),
    path('explore/tags/<tag>/', post_list, name="post_search"),
    path('<int:pk>/', post_detail, name='post_detail'),
    path('comment_detail/new/', comment_new_detail, name='comment_new_detail'),
    path('<username>/list/detail/', my_post_list, name='my_post_list'),
]

post/models.py
from django.conf import settings
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import re


def photo_path(instance, filename):
    from time import strftime
    from random import choice
    import string

    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    return f"{strftime('post/%Y/%m/%d/')}/{instance.author.username}/{pid}.{extension}"

    # return '{}/{}/{}.{}'.format(strftime('post/%Y/%m/%d/'),
    #                             instance.author.username, pid, extension)


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    photo = ProcessedImageField(upload_to=photo_path, processors=[
        ResizeToFill(600, 600)], format='JPEG', options={'quality': 90})

    content = models.CharField(max_length=140, help_text="최대 140자 입력 가능")
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                           blank=True,
                                           related_name='like_user_set',
                                           through='Like')

    bookmark_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                               blank=True,
                                               related_name='bookmark_user_set',
                                               through='Bookmark')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tag_set = models.ManyToManyField('Tag', blank=True)

    # 생성 시간 기준으로 정렬
    class Meta:
        ordering = ['-created_at']

    # content에서 tags를 추출하여, Tag 객체 가져오기, 신규 태그는 Tag instance 생성, 본인의 tag_set에 등록
    def tag_save(self):
        tags = re.findall(r'#(\w+)\b', self.content)

        if not tags:
            return

        for t in tags:
            tag, tag_created = Tag.objects.get_or_create(name=t)
            self.tag_set.add(tag)  # ManyToManyField에 인스턴스 추가

    @property
    def like_count(self):
        return self.like_user_set.count()

    @property
    def bookmark_count(self):
        return self.bookmark_user_set.count()

    def __str__(self):
        return self.content


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            ('user', 'post')
        )


class Bookmark(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            ('user', 'post')
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    content = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=140, unique=True)

    def __str__(self):
        return self.name

post/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    photo = forms.ImageField(label='', required=False)
    content = forms.CharField(label='', widget=forms.Textarea(attrs={
        'class': 'post-new-content',
        'rows': 5,
        'cols': 50,
        'placeholder': '140자까지 등록 가능합니다.'
    }))

    class Meta:
        model = Post
        fields = ['photo', 'content']


class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.TextInput(attrs={
        'class': 'comment-form',
        'size': '70px',
        'placeholder': '댓글 달기...',
        'maxlength': '40', }))

    class Meta:
        model = Comment
        fields = ['content']

post/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.http import HttpResponse
import json
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from .forms import CommentForm
from .admin import PostForm
from django.db.models import Count
from .models import Post, Comment, Like, Tag


def post_list(request, tag=None):
    # if tag:
    #     post_list = Post.objects.filter(tag_set__name__iexact=tag)
    # else:
    #     post_list = Post.objects.all()
    # posts = Post.objects.all()

    if tag:
        post_list = Post.objects.filter(tag_set__name__iexact=tag) \
            .prefetch_related('tag_set', 'like_user_set__profile', 'comment_set__author__profile',
                              'author__profile__follower_user', 'author__profile__follower_user__from_user') \
            .select_related('author__profile')
    else:
        post_list = Post.objects.all() \
            .prefetch_related('tag_set', 'like_user_set__profile', 'comment_set__author__profile',
                              'author__profile__follower_user', 'author__profile__follower_user__from_user') \
            .select_related('author__profile')

    comment_form = CommentForm()

    paginator = Paginator(post_list, 3)
    page_num = request.POST.get('page')

    try:
        posts = paginator.page(page_num)
    except PageNotAnInteger:  # page 파라미터가 int가 아닌 값이 들어오게 되면 page(1)로 변경
        posts = paginator.page(1)
    except EmptyPage:  # page가 페이지를 넘어서면 마지막 페이지를 넘겨줌.
        posts = paginator.page(paginator.num_pages)

    if request.is_ajax():
        return render(request, 'post/post_list_ajax.html', {
            'posts': posts,
            'comment_form': comment_form,
        })

    if request.method == 'POST':
        tag = request.POST.get('tag')
        tag_clean = ''.join(e for e in tag if e.isalnum())
        return redirect('post:post_search', tag_clean)

    if request.user.is_authenticated:
        username = request.user
        user = get_object_or_404(get_user_model(), username=username)
        user_profile = user.profile

        follow_set = request.user.profile.get_following
        following_post_list = Post.objects.filter(author__profile__in=follow_set)

        return render(request, 'post/post_list.html', {
            'user_profile': user_profile,
            # 'tag': tag,
            'posts': posts,
            'comment_form': comment_form,
            'following_post_list': following_post_list,
        })
    else:
        return render(request, 'post/post_list.html', {
            # 'tag': tag,
            'posts': posts,
            'comment_form': comment_form,
        })


@login_required  # 데코레이터 : 로그인 상태인 경우에만 작동하는 함수
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            # 유저 정보를 넣은 뒤 저장하기 위해 commit = False 옵션을 줌.
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag_save()
            messages.info(request, '새 글이 등록되었습니다.')
            return redirect('post:post_list')
    else:
        form = PostForm()
    return render(request, 'post/post_new.html', {
        'form': form,
    })


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:  # post data와 request data가 다르다면 경고
        messages.warning(request, '잘못된 접근입니다')
        return redirect('post:post_list')

    if request.method == 'POST':  # POST요청이라면 PostForm에 요청정보 넣기
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            # post.tag_set.clear()
            # post.tag_save()
            messages.success(request, '수정완료')
            return redirect('post:post_list')
    else:
        form = PostForm(instance=post)

    return render(request, 'post/post_edit.html', {
        'post': post,
        'form': form,
    })


@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # URL을 통한 DB 접근 방지
    if post.author != request.user or request.method != 'POST':
        messages.warning(request, '잘못된 접근입니다.')
    else:
        post.delete()
        # messages.success(request, '삭제완료')
    return redirect('post:post_list')


@login_required
@require_POST
def post_like(request):
    pk = request.POST.get('pk', None)
    post = get_object_or_404(Post, pk=pk)
    post_like, post_like_created = post.like_set.get_or_create(
        user=request.user)

    if not post_like_created:
        post_like.delete()
        message = "좋아요 취소"
    else:
        message = "좋아요"

    context = {'like_count': post.like_count,
               'message': message}

    return HttpResponse(json.dumps(context), content_type="application/json")


@login_required
@require_POST
def post_bookmark(request):
    pk = request.POST.get('pk', None)
    post = get_object_or_404(Post, pk=pk)
    post_bookmark, post_bookmark_created = post.bookmark_set.get_or_create(
        user=request.user)

    if not post_bookmark_created:
        post_bookmark.delete()
        message = "북마크 취소"
    else:
        message = "북마크"

    context = {'bookmark_count': post.bookmark_count,
               'message': message}

    return HttpResponse(json.dumps(context), content_type="application/json")


@login_required
def comment_new(request):
    pk = request.POST.get('pk')  # Ajax 통신 부분
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return render(request, 'post/comment_new_ajax.html', {
                'comment': comment,
            })
        return redirect("post:post_list")


@login_required
def comment_new_detail(request):
    pk = request.POST.get('pk')  # Ajax 통신 부분
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return render(request, 'post/comment_new_ajax.html', {
                'comment': comment,
            })
        return redirect("post:post_list")


@login_required
def comment_delete(request):
    pk = request.POST.get('pk')
    comment = get_object_or_404(Comment, pk=pk)
    if request.method == 'POST' and request.user == comment.author:
        comment.delete()
        message = '삭제완료'
        status = 1

    else:
        message = '잘못된 접근입니다'
        status = 0

    return HttpResponse(json.dumps({'message': message, 'status': status, }), content_type="application/json")


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm()

    return render(request, 'post/post_detail.html', {
        'comment_form': comment_form,
        'post': post,
    })


def comment_new_detail(request):
    pk = request.POST.get('pk')
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return render(request, 'post/comment_new_detail_ajax.html', {
                'comment': comment,
            })


def my_post_list(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    user_profile = user.profile
    target_user = get_user_model().objects.filter(id=user.id)
    # target_user = get_user_model().objects.filter(id=user.id) \
    #     .select_related('profile') \
    #     .profetch_related('profile__follower_user__from_user', 'profile__follow_user__to_user')

    post_list = user.post_set.all()
    all_post_list = Post.objects.all()

    return render(request, 'post/my_post_list.html', {
        'user_profile': user_profile,
        'target_user': target_user,
        'post_list': post_list,
        'all_post_list': all_post_list,
        'username': username,
    })

post/templates/post/comment_new_ajax.html
<div class="comment-detail" id="comment{{ comment.id }}">
    <div class="nick_name m_text">{{ comment.author.profile.nickname }}</div>
    <div>{{ comment.content }}</div>
    {% if user == comment.author %}
        <input type="button" class="del-comment" data-name="comment-delete" value="삭제" name="{{ comment.id }}">
    {% endif %}
</div>

post/templates/post/post_edit.html
{% extends "post/layout.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/new_post.css' %}">
{% endblock %}

{% block content %}
    <div id="main_container">
        <div class="post_form_container">
            <form action="#" class="post_form" method="post"
                  enctype="multipart/form-data">
                <div class="title">
                    Edit Post
                </div>
                <!-- 새글 작성이랑 비슷하지만 수정은 이미 올라가 있는 이미지 불러오고 교체 -->
                <div class="preview">
                    <div class="upload">
                        <div class="post_btn">
                            {% if post %}
                                <p><img id="img_id" src="{{ post.photo.url }}"
                                        style="width: 300px; height: 300px;
                                    object-fit: cover">
                                </p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% csrf_token %}
                {{ form.as_p }}

                <input class="submit_btn" type="submit" value="수정완료">
            </form>
        </div>
    </div>

    <script>
        const photo = document.querySelector('#img_id');

        function upload_img(input) {
            let reader = new FileReader();
            if (input.files && input.files[0]) {
                reader.onload = function (e) {
                    photo.setAttribute('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        let idPhoto = document.querySelector('#id_photo');

        idPhoto.addEventListener('change', function () {
            upload_img(this);
        });
    </script>
{% endblock %}

post/templates/post/script_ajax.html
<script type="text/javascript">
    (function () {
        const delegation = document.querySelector('.contents_box');
        const side_box = document.querySelector('.side_box');
        const header = document.querySelector('#header');

        function delegationFunc(e) {
            let elem = e.target;
            console.log(elem);

            while (!elem.getAttribute('data-name')) {
                elem = elem.parentNode;

                if (elem.nodeName === 'BODY') {
                    elem = null;
                    return;
                }
            }
            if (elem.matches('[data-name="heartbeat"]')) {
                console.log('하트!')
                let pk = elem.getAttribute('name');
                console.log(pk);

                $.ajax({
                    type: "POST",
                    url: "{% url 'post:post_like' %}",
                    data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    dataType: "json",
                    success: function (response) {
                        {#alert('성공!')#}
                        let likeCount = document.querySelector
                        ('#like-count-' + pk);
                        likeCount.innerHTML = '좋아요' + response.like_count + '개'
                    },
                    error: function (request, status, error) {
                        alert("code:" + request.status + "\n" + "message:" +
                            request.responseText + "\n" + "error" + error);
                    },
                });
            } else if (elem.matches('[data-name="bookmark"]')) {
                console.log('북마크!');

                let pk = elem.getAttribute('name');
                console.log(pk)

                $.ajax({
                    type: "POST",
                    url: "{% url 'post:post_bookmark' %}",
                    data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    dataType: "json",
                    success: function (response) {
                        {#alert('성공!')#}
                        let bookmarkCount = document.querySelector
                        ('#bookmark-count-' + pk);
                        bookmarkCount.innerHTML = '좋아요' + response.bookmark_count +
                            '개'
                    },
                    error: function (request, status, error) {
                        alert("code:" + request.status + "\n" + "message:" +
                            request.responseText + "\n" + "error" + error);
                    },
                });
            } else if (elem.matches('[data-name="comment"]')) {
                console.log('새댓글')
                let pk = elem.getAttribute('name');
                let content = document.querySelector('#add-comment-post' + pk + '>input[type=text]').value;
                console.log(content)

                if (content.length > 140) {
                    alert("댓글은 최대 140자 입력 가능합니다. 현재 글자수 :" + content.length);
                    return;
                }

                if (content.length == 0) {
                    alert("글자를 하나라도 넣어주세요. 현재 글자수 :" + content.length);
                    return;
                }


                $.ajax({
                    type: "POST",
                    url: "{% url 'post:comment_new' %}",
                    data: {
                        'pk': pk,
                        'content': content,
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    dataType: "html",
                    success: function (data, textStatus, jqXHR) {
                        console.log("성공!")
                        document.querySelector("#comment-list-ajax-post" + pk).insertAdjacentHTML("afterbegin", data);
                    },
                    error: function (request, status, error) {
                        alert("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);
                    },
                });
            } else if (elem.matches('[data-name="comment_delete"]')) {
                let pk = elem.getAttribute('name');

                $.ajax({
                    type: "POST",
                    url: "{% url 'post:comment_delete' %}",
                    data: {
                        'pk': pk,
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    dataType: "json",
                    success: function (response) {
                        if (response.status) {
                            document.querySelector('#comment' + pk).remove();
                        }
                    },
                    error: function (request, status, error) {
                        alert("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);
                    }
                });
            } else if (elem.matches('[data-name="follow"]')) {
                console.log("팔로우!");
                let pk = elem.getAttribute('name');

                $.ajax({
                    type: "post",
                    url: "{% url 'accounts:follow' %}",
                    data: {
                        'pk': pk,
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    dataType: "json",
                    success: function (response) {
                        console.log("성공");
                        if (response.status) {
                            document.querySelector('input.follow[name=\'' + pk + '\']').value = "팔로잉";
                        } else {
                            document.querySelector('input.follow[name=\'' + pk + '\']').value = "팔로우";
                        }
                    },
                    error: function (request, status, error) {
                        alert('code:' + request.status + '\n' + 'message:' + request.responseText + '\n' + 'error:' + error);
                    }
                })
            }
            elem.classList.toggle('on')
        }

        function resizefunc() {
            console.log('리사이즈')
            if (pageYOffset >= 10) {
                let calcWidth = (window.innerWidth * 0.5) + 167;
                if (side_box) {
                    side_box.style.left = calcWidth + "px";
                }
            }
        }

        function scrollfunc() {
            let scrollHeight = pageYOffset + window.innerHeight;
            let documentHeight = document.body.scrollHeight;

            console.log(pageYOffset);
            console.log('scrollHeight:' + scrollHeight);
            console.log('documentHeight:' + documentHeight);

            if (pageYOffset >= 10) {
                header.classList.add('on');
                resizefunc();
                if (side_box) {
                    side_box.classList.add('on');
                }
            } else {
                header.classList.remove('on');
                if (side_box) {
                    side_box.classList.remove('on');
                    side_box.removeAttribute('style');
                }
            }

            if (scrollHeight >= documentHeight) {
                let page = document.querySelector('#page').value;
                console.log(page);
                let end_page =
                {{ posts.paginator.num_pages }} // 해당 내용은 views.py에서 작성

                if (page > end_page) {
                    return;
                }

                document.querySelector('#page').value = parseInt(page) + 1;
                callMorePostAjax(page);
            }
        }

        function callMorePostAjax(page) {
            let end_page = {{ posts.paginator.num_pages }}; // post의 페이지 수를 불러오는 작업

            if (page > end_page) {
                return;
            }

            $.ajax({
                type: 'POST',
                url: "{% url 'post:post_list' %}",
                data: {
                    'page': page,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                    // csrf_token은 누가 요청할 때 서버에서 암호화 된 토큰 값을 받고 그것을 다시 서버로 전송해서 두개의 값을 비교해
                    // 우리가 보낸 토큰이 맞는지 확인하여 중간에 해킹 시도를 막는 기능을 함.
                },
                dataType: 'html',
                success: addMorePostAjax,
                error: function (request, status, error) {
                    alert("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);
                }
            });
        }

        // 새로 받은 post_list html을 post 뒤에다가 계속 누적해서 붙이는 함수
        function addMorePostAjax(data, textStatus, jqXHR) {
            let post = document.querySelector('#post_list_ajax');
            post.insertAdjacentHTML('beforeend', data);
        }

        // 뷰의 크기가 변할 때 resizefunc 함수 실행
        window.addEventListener('resize', resizefunc);

        // 스크롤이 이동했을 때 scrollfunc 함수 실행
        window.addEventListener('scroll', scrollfunc);
        delegation.addEventListener('click', delegationFunc);
    })()
</script>

post/templates/post/script_ajax_detail.html
<script type="text/javascript">
    (function () {
        const delegation = document.querySelector('.contents_box')


        function delegationFunc(e) {
            let elem = e.target;

            while (!elem.getAttribute('data-name')) {
                elem = elem.parentNode;

                if (elem.nodeName === 'BODY') {
                    elem = null;
                    return;
                }
            }

            if (elem.matches('[data-name="follow"]')) {
                console.log('팔로우');

                var pk = elem.getAttribute('name')

                $.ajax({
                    type: "POST",
                    url: "{% url 'accounts:follow' %}",
                    data: {
                        'pk': pk,
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    dataType: "json",
                    success: function (response) {
                        // alert('성공!')
                        if (response.status) {
                            document.querySelector('input.follow[name=\'' + pk + '\']').value = "팔로잉";
                        } else {
                            document.querySelector('input.follow[name=\'' + pk + '\']').value = "팔로우";
                        }


                    },
                    error: function (request, status, error) {
                        alert("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);
                    },
                })
            } else if (elem.matches('[data-name="heartbeat"]')) {
                var pk = elem.getAttribute('name')

                $.ajax({
                    type: "POST",
                    url: "{% url 'post:post_like' %}",
                    data: {
                        'pk': pk,
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    dataType: "json",
                    success: function (response) {
                        // alert('성공!')
                        var likeCount = document.querySelector('#like-count-' + pk);
                        likeCount.innerHTML = '좋아요' + response.like_count + '개';


                    },
                    error: function (request, status, error) {
                        alert("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);
                    },
                })
            } else if (elem.matches('[data-name="bookmark"]')) {
                var pk = elem.getAttribute('name')

                $.ajax({
                    type: "POST",
                    url: "{% url 'post:post_bookmark' %}",
                    data: {
                        'pk': pk,
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    dataType: "json",
                    success: function (response) {
                        // alert('성공!');
                        var bookmarkCount = document.querySelector('#bookmark-count-' + pk);
                        bookmarkCount.innerHTML = '북마크' + response.bookmark_count + '개';
                    },
                    error: function (request, status, error) {
                        alert("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);
                    },
                })
            } else if (elem.matches('[data-name="comment"]')) {
                var pk = elem.getAttribute('name');
                var content = document.querySelector('#add-comment-post' + pk + '>input[type=text]').value;

                if (content.length > 140) {
                    alert("댓글은 최대 140자 입력 가능합니다. 현재 글자수 :" + content.length);
                }

                if (content.length == 0) {
                    alert("한글자 이상 입력해 주세요. 현재 글자수 :" + content.length);
                }

                $.ajax({
                    type: "POST",
                    url: "{% url 'post:comment_new_detail' %}",
                    data: {
                        'pk': pk,
                        'content': content,
                        'csrfmiddlewaretoken': '{{ csrf_token}}',
                    },
                    dataType: "html",
                    success: function (data, textStatus, jqXHR) {
                        document.querySelector("#comment-list-ajax-post" + pk).insertAdjacentHTML("afterbegin", data);
                    },
                    error: function (reqeust, status, error) {
                        alert("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);
                    },
                });
            } else if (elem.matches('[data-name="comment_delete"]')) {
                var pk = elem.getAttribute('name');

                $.ajax({
                    type: "POST",
                    url: "{% url 'post:comment_delete' %}",
                    data: {
                        'pk': pk,
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    dataType: "json",
                    success: function (response) {
                        if (response.status) {
                            document.querySelector('#comment' + pk).remove();
                        }

                    },
                    error: function (reqeust, status, error) {
                        alert("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);
                    },
                })

            }


            elem.classList.toggle('on');
        }

        delegation.addEventListener('click', delegationFunc);
    })();
</script>