Django_instaclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),  # accounts app url 연결
    path('accounts/', include('allauth.urls')),

    path('post/', include('post.urls', namespace='post')),  # post app url 연결
    # 루트 URL로 접근할 때 post로 연결
    path('', lambda r: redirect('post:post_list'), name='root'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login_check, name='login'),
    path('logout/', logout, name='logout'),
    path('follow/', follow, name="follow"),
]

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('new/', post_new, name='post_new'),  # 새 포스트 작성 url
    path('edit/<int:pk>/', post_edit, name='post'
                                           '_edit'),  # <int:pk> 키값.
    path('delete/<int:pk>/', post_delete, name='post_delete'),
    path('like/', post_like, name="post_like"),
    path('bookmark/', post_bookmark, name="post_bookmark"),
    path('comment/new/', comment_new, name="comment_new"),
    path('comment/delete/', comment_delete, name='comment_delete'),
    path('explore/tags/<tag>/', post_list, name="post_search"),
    path('<int:pk>/', post_detail, name='post_detail'),
    path('comment_detail/new/', comment_new_detail, name='comment_new_detail'),
    path('<username>/list/detail/', my_post_list, name='my_post_list'),
]

Django_instaclone/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">

    <!-- Facebook Meta Tags / 페이스북 오픈 그래프 -->
    <meta property="og:url" content="http://kindtiger.dothome.co.kr/insta">
    <meta property="og:type" content="website">
    <meta property="og:title" content="instagram">
    <meta property="og:description" content="instagram clone">
    <meta property="og:image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">
    .
    <!-- Twitter Meta Tags / 트위터 -->
    <meta name="twitter:card" content="instagram clone">
    <meta name="twitter:title" content="instagram">
    <meta name="twitter:description" content="instagram clone">
    <meta name="twitter:image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">

    <!-- Google / Search Engine Tags / 구글 검색 엔진 -->
    <meta itemprop="name" content="instagram">
    <meta itemprop="description" content="instagram clone">
    <meta itemprop="image" content="http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg">


    <title>instagram</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="shortcut icon" href="{% static 'imgs/instagram.png' %}">

    {% block head %}
    {% endblock %}


</head>
<body>
<section id="container">


    <header id="header">
        <section class="h_inner">

            <h1 class="logo">
                <a href="{% url 'post:post_list' %}">
                    <div class="sprite_insta_icon"></div>
                    <div>
                        <div class="sprite_write_logo"></div>
                    </div>
                </a>
            </h1>

            <div class="search_field">
                <input type="text" placeholder="검색" tabindex="0">

                <div class="fake_field">
                    <span class=sprite_small_search_icon></span>
                    <span>검색</span>
                </div>
            </div>


            <div class="right_icons">
                <div class="sprite_camera_icon"><a href="{% url 'post:post_new' %}"></a></div>
                <div class="sprite_compass_icon"><a href="#"></a></div>
                <div class="sprite_heart_icon_outline"><a href="follow.html"></a></div>

                {% if user.is_authenticated %}

                    <div class="sprite_user_icon_outline"><a href="{% url 'post:my_post_list' user.username %}"></a></div>

                {% else %}

                    <div class="sprite_user_icon_outline"><a href="{% url 'accounts:login' %}"></a></div>

                {% endif %}
            </div>
        </section>
    </header>

    {% block content %}
    {% endblock %}

</section>

<!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요합니다) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<!-- <script src="{% static 'js/insta.js' %}"></script> -->
{% block js %}
{% endblock %}


</body>
</html>